### ISSUE TITLE
In larger screen, website does not fit the whole screen (whitespace on it's leftmost and rightmost part)

### ISSUE THREAD

**Issue by brianrahadi** [ssss-sfu/systemshacks#10]
![image](https://user-images.githubusercontent.com/70176191/212522331-327c0916-89fa-437a-86e4-138145d37f7d.png)

Screen Size:
27-inch (1920 x 1080)

**Comment by KiaanCastillo** [comment]
Resolved via PR #12 by adding the gradient background to the `body` tag, getting rid of the white margins.
